# Generated by Django 4.1.1 on 2022-09-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_insurance"),
    ]

    operations = [
        migrations.RenameModel(old_name="Insurance", new_name="Insuranced",),
    ]
