# Generated by Django 4.1.1 on 2022-10-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='start_date',
        ),
    ]
